package testEjemplotp2;

public enum MenuPrincipal {
AGREGAR_HAMBURGUESA,
MODIFICAR_HAMBURGUESA,
ELIMINAR_HAMBURGUESA,
BUSCAR_HAMBURGUESA_POR_ID,//
MOSTRAR_HAMBURGUESA_DE_UN_TIPO_DE_PAN,//
MOSTRAR_LA_HAMBURGUESA_MAS_CARA,//
MOSTRAR_PROMEDIO_DE_PRECIO_HAMBURGUESA_DE_UN_TIPO_DE_PAN,//
MOSTRAR_PRECIO_TOTAL_HAMBURGUESAS,
SALIR
}
